# Docker Compose配置文件
# version字段已过时，移除以使用最新版本

# 设置默认网络配置
x-logging: &default-logging
  driver: "json-file"
  options:
    max-size: "10m"
    max-file: "3"

services:
  # Spring Boot应用
  springmvc-app:
    build:
      context: .
      dockerfile: Dockerfile.aliyun-stable
    container_name: springmvc-demo
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_NAME=springmvc_demo
      - DB_USERNAME=springmvc_user
      - DB_PASSWORD=springmvc_password
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=redis_password
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USERNAME=admin
      - RABBITMQ_PASSWORD=admin123
      - RABBITMQ_VHOST=/prod
      - SILICONFLOW_API_KEY=${SILICONFLOW_API_KEY}
    depends_on:
      - mysql
      - redis
      - rabbitmq
    networks:
      - app-network
    volumes:
      - ./logs:/var/log/springmvc-demo
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    restart: unless-stopped
    logging: *default-logging

  # MySQL数据库
  mysql:
    image: him7zrbc.mirror.aliyuncs.com/library/mysql:8.0
    container_name: mysql-db
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_DATABASE=springmvc_demo
      - MYSQL_USER=springmvc_user
      - MYSQL_PASSWORD=springmvc_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./docker/mysql/light-my.cnf:/etc/mysql/conf.d/custom.cnf
    networks:
      - app-network
    restart: unless-stopped
    logging: *default-logging
    command: --default-authentication-plugin=mysql_native_password

  # Redis缓存
  redis:
    image: him7zrbc.mirror.aliyuncs.com/library/redis:alpine
    container_name: redis-cache
    ports:
      - "6379:6379"
    command: redis-server --requirepass redis_password
    volumes:
      - redis_data:/data
    networks:
      - app-network
    restart: unless-stopped
    logging: *default-logging
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

  # RabbitMQ消息队列
  rabbitmq:
    image: him7zrbc.mirror.aliyuncs.com/library/rabbitmq:3.8-management
    container_name: rabbitmq-mq
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin123
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - app-network
    restart: unless-stopped
    logging: *default-logging

  # Nginx反向代理
  nginx:
    image: him7zrbc.mirror.aliyuncs.com/library/nginx:1.21-alpine
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - springmvc-app
    networks:
      - app-network
    restart: unless-stopped
    logging: *default-logging

volumes:
  mysql_data:
  redis_data:
  rabbitmq_data:

networks:
  app-network:
    driver: bridge