# Spring Boot 应用配置
server:
  port: 8080
  servlet:
    context-path: /api
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  profiles:
    active: dev
    
  # 应用信息
  application:
    name: springmvc-demo
  
  # Spring AI配置
  ai:
    openai:
      api-key: 1234567890
      base-url: https://api.siliconflow.cn/v1
      chat:
        options:
          model: Qwen/QwQ-32B
          temperature: 0.7
    
  # 数据源配置（开发环境将使用H2内存数据库）
  datasource:
    # 生产环境数据库配置（待接入阿里云数据库时启用）
    # url: ${DB_URL:jdbc:mysql://localhost:3306/springmvc_demo?useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true}
    # username: ${DB_USERNAME:root}
    # password: ${DB_PASSWORD:password}
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      # 初始连接数
      initial-size: 5
      # 最小连接池数量
      min-idle: 10
      # 最大连接池数量
      max-active: 20
      # 配置获取连接等待超时的时间
      max-wait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 300000
      # 配置一个连接在池中最大生存的时间，单位是毫秒
      max-evictable-idle-time-millis: 900000
      # 配置检测连接是否有效
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      
  # JPA配置
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
        
  # Redis配置（暂时禁用，后续接入阿里云Redis时启用）
  # redis:
  #   host: ${REDIS_HOST:localhost}
  #   port: ${REDIS_PORT:6379}
  #   password: ${REDIS_PASSWORD:}
  #   database: ${REDIS_DATABASE:0}
  #   timeout: 3000ms
  #   lettuce:
  #     pool:
  #       max-active: 8
  #       max-wait: -1ms
  #       max-idle: 8
  #       min-idle: 0
        
  # RabbitMQ配置（暂时禁用，后续需要时启用）
  # rabbitmq:
  #   host: ${RABBITMQ_HOST:localhost}
  #   port: ${RABBITMQ_PORT:5672}
  #   username: ${RABBITMQ_USERNAME:guest}
  #   password: ${RABBITMQ_PASSWORD:guest}
  #   virtual-host: ${RABBITMQ_VHOST:/}
  #   publisher-confirm-type: correlated
  #   publisher-returns: true
  #   listener:
  #     simple:
  #       acknowledge-mode: manual
  #       concurrency: 1
  #       max-concurrency: 10
  #       retry:
  #         enabled: true
  #         max-attempts: 3
  #         initial-interval: 1000ms
          
  # Jackson配置
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    serialization:
      write-dates-as-timestamps: false
      
# 日志配置
logging:
  level:
    com.example.springmvc: debug
    org.springframework.web: debug
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/application.log
    max-size: 100MB
    max-history: 30
    
# 管理端点配置
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized